import { ref } from 'vue';

export const allDocuments = ref([
    {
      id: 1,
      date: '13',
      month: 'Des',
      number: 324,
      title: 'KEPUTUSAN GUBERNUR Nomor 324 Tahun 2024',
      description: 'Keputusan Gubernur Lampung Nomor 324 Tahun 2024 Tentang Perubahan Atas Lampiran Keputusan Gubernur Lampung Nomor: G/85/B.06/Hk/2024 Tentang Penunjukan Kuasa Pengguna Anggaran, Pejabat Pembuat Komitmen, Pejabat Penandatanganan Surat Perintah Membatar Dan Bendahara Pengeluaran Anggaran Pendapatan Dan Belanja Negara/Dekonsentrasi Pada Dinas Kesehatan Provinsi Lampung Tahun Anggaran 2024 Diterbitkan Di Biro Hukum,2024 Dengan Subjek Perubahan Atas Lampiran Keputusan Gubernur Lampung Nomor: G/85/B.06/HK/2024',
      year: 2024,
      downloads: 2,
      views: 4,
      kategori: 1,
      abstrak: "Abstrak",
      file:"Abstrak",
      teu:"LAMPUNG (PROVINSI), BIRO HUKUM",
      singkatan:"KEPGUB",
      tglundang:"13 Des 2024",
      subjek:"Perubahan Atas Lampiran Keputusan Gubernur Lampung Nomor: G/85/B.06/HK/2024",
      status:"Masih Berlaku",
      sumber:"Tidak ada sumber",
      tptterbit:"BIRO HUKUM, 2024",
      bidang:"Hukum Tata Negara",
      bahasa:"INDONESIA",
      lokasi:"Biro Hukum Provinsi Lampung"
    },
    {
      id: 2,
      date: '13',
      month: 'Des',
      number: 326,
      title: 'KEPUTUSAN GUBERNUR Nomor 324 Tahun 2024',
      description: 'Tentang Penunjukan Kuasa Penguna Anggara, Pejabat Pembuat Komitmen, Peabat Pendatanganan Surat Perintah Membatar dan Bendahara Pengeluaran Anggaran Pendapatan dan Belanja Negara/Dekonsentrasi Pada Dinas KEsehatan Provinsi Lampung Tahun Anggara 2024',
      year: 2024,
      downloads: 2,
      views: 4,
      kategori: 1,
      abstrak: "",
      file:"",
      teu:"",
      singkatan:"",
      tgltetap:"",
      tglundang:"",
      subjek:"",
      status:"",
      sumber:"",
      tptterbit:"",
      bidang:"",
      bahasa:"",
      lokasi:""
    },
    {
      id: 3,
      date: '13',
      month: 'Des',
      number: 326,
      title: 'KEPUTUSAN GUBERNUR Nomor 324 Tahun 2024',
      description: 'Tentang Penunjukan Kuasa Penguna Anggara, Pejabat Pembuat Komitmen, Peabat Pendatanganan Surat Perintah Membatar dan Bendahara Pengeluaran Anggaran Pendapatan dan Belanja Negara/Dekonsentrasi Pada Dinas KEsehatan Provinsi Lampung Tahun Anggara 2024',
      year: 2024,
      downloads: 2,
      views: 4,
      kategori: 1,
      abstrak: "",
      file:"",
      teu:"",
      singkatan:"",
      tgltetap:"",
      tglundang:"",
      subjek:"",
      status:"",
      sumber:"",
      tptterbit:"",
      bidang:"",
      bahasa:"",
      lokasi:""
    },
    {
      id: 4,
      date: '13',
      month: 'DES',
      number: 326,
      title: 'KEPUTUSAN GUBERNUR Nomor 324 Tahun 2024',
      description: 'Tentang Penunjukan Kuasa Penguna Anggara, Pejabat Pembuat Komitmen, Peabat Pendatanganan Surat Perintah Membatar dan Bendahara Pengeluaran Anggaran Pendapatan dan Belanja Negara/Dekonsentrasi Pada Dinas KEsehatan Provinsi Lampung Tahun Anggara 2024',
      year: 2024,
      downloads: 2,
      views: 4,
      kategori: 1,
      abstrak: "",
      file:"",
      teu:"",
      singkatan:"",
      tgltetap:"",
      tglundang:"",
      subjek:"",
      status:"",
      sumber:"",
      tptterbit:"",
      bidang:"",
      bahasa:"",
      lokasi:""
    },
    {
      id: 5,
      date: '13',
      month: 'DES',
      number: 326,
      title: 'KEPUTUSAN GUBERNUR Nomor 320 Tahun 2023',
      description: 'Tentang Penunjukan Kuasa Penguna Anggara, Pejabat Pembuat Komitmen, Peabat Pendatanganan Surat Perintah Membatar dan Bendahara Pengeluaran Anggaran Pendapatan dan Belanja Negara/Dekonsentrasi Pada Dinas KEsehatan Provinsi Lampung Tahun Anggara 2024',
      year: 2023,
      downloads: 2,
      views: 4,
      kategori: 1,
      abstrak: "",
      file:"",
      teu:"",
      singkatan:"",
      tgltetap:"",
      tglundang:"",
      subjek:"",
      status:"",
      sumber:"",
      tptterbit:"",
      bidang:"",
      bahasa:"",
      lokasi:""
    },
    {
      id: 6,
      date: '13',
      month: 'DES',
      number: 326,
      title: 'KEPUTUSAN GUBERNUR Nomor 320 Tahun 2023',
      description: 'Tentang Penunjukan Kuasa Penguna Anggara, Pejabat Pembuat Komitmen, Peabat Pendatanganan Surat Perintah Membatar dan Bendahara Pengeluaran Anggaran Pendapatan dan Belanja Negara/Dekonsentrasi Pada Dinas KEsehatan Provinsi Lampung Tahun Anggara 2024',
      year: 2023,
      downloads: 2,
      views: 4,
      kategori: 6,
      abstrak: "",
      file:"",
      teu:"",
      singkatan:"",
      tgltetap:"",
      tglundang:"",
      subjek:"",
      status:"",
      sumber:"",
      tptterbit:"",
      bidang:"",
      bahasa:"",
      lokasi:""
    },
    {
      id: 7,
      date: '13',
      month: 'DES',
      number: 326,
      title: 'KEPUTUSAN GUBERNUR Nomor 320 Tahun 2023',
      description: 'Tentang Penunjukan Kuasa Penguna Anggara, Pejabat Pembuat Komitmen, Peabat Pendatanganan Surat Perintah Membatar dan Bendahara Pengeluaran Anggaran Pendapatan dan Belanja Negara/Dekonsentrasi Pada Dinas KEsehatan Provinsi Lampung Tahun Anggara 2024',
      year: 2023,
      downloads: 2,
      views: 4,
      kategori: 7,
      abstrak: "",
      file:"",
      teu:"",
      singkatan:"",
      tgltetap:"",
      tglundang:"",
      subjek:"",
      status:"",
      sumber:"",
      tptterbit:"",
      bidang:"",
      bahasa:"",
      lokasi:""
    }
    ]);