import { ref } from 'vue'

export const allDocuments = ref([
  {
    id: 1,
    date: '10',
    month: 'Jan',
    number: 1,
    title: 'PERATURAN DAERAH No. 1 Tahun 2024',
    description:
      'Peraturan Daerah Provinsi Lampung Nomor 1 Tahun 2024 Tentang Produk Lokal Unggulan Diterbitkan di Biro Hukum,2024 dengan Subjek Produk Lokal Unggulan',
    year: 2024,
    downloads: 2,
    views: 4,
    kategori: 1,
    abstrak: 'https://jdih.lampungprov.go.id/uploads/abstrak/2024/01/abstrak_1710816413954.pdf',
    fileverasing: '',
    teu: 'LAMPUNG (PROVINSI), BIRO HUKUM',
    singkatan: 'PERDA',
    tglundang: '10 Januari 2024',
    subjek: 'Produk Lokal Unggulan',
    status: "Masih Berlaku",
    sumber: 'LD 2024 (1); 14hlm',
    tptterbit: 'BIRO HUKUM, 2024',
    bidang: 'Hukum Tata Negara',
    bahasa: 'INDONESIA',
    lokasi: 'Biro Hukum Provinsi Lampung',
    link: 'https://jdih.lampungprov.go.id/product-hukum/provinsi/10872/pdf/penunjukan-koordinator-pengelolaan-keuangan-daerah-anggaran-pendapatan-dan-belanja-daerah-provinsi-lampung-tahun-anggaran-2024?req-download=file'
  },
  {
    id: 2,
    date: '10',
    month: 'Jan',
    number: 2,
    title: 'PERATURAN DAERAH No. 2 Tahun 2024',
    description:
      'Peraturan Daerah Provinsi Lampung Nomor 2 Tahun 2024 Tentang Penyelenggaraan Perpustakaan Dan Arsip Elektronik Diterbitkan Di Biro Hukum,2024 Dengan Subjek Perpustakan Dan Kearsipan',
    year: 2024,
    downloads: 2,
    views: 4,
    kategori: 1,
    abstrak: 'https://jdih.lampungprov.go.id/uploads/abstrak/2024/01/abstrak_1708073564568.pdf',
    fileverasing: '',
    teu: 'LAMPUNG (PROVINSI), BIRO HUKUM',
    singkatan: 'PERDA',
    tglundang: '10 Januari 2024',
    subjek: 'Perpustakan dan Kearsipan',
    status: "Masih Berlaku",
    sumber: 'LD 2024 (1); 14hlm',
    tptterbit: 'BIRO HUKUM, 2024',
    bidang: 'Hukum Tata Negara',
    bahasa: 'INDONESIA',
    lokasi: 'Biro Hukum Provinsi Lampung',
    link: 'https://jdih.lampungprov.go.id/product-hukum/provinsi/10902/pdf/penyelenggaraan-perpustakaan-dan-arsip-elektronik?req-download=file'
  },
  {
    id: 3,
    date: '12',
    month: 'Feb',
    number: 5,
    title: 'PERATURAN DAERAH No. 5 Tahun 2024',
    description:
      'Peraturan Daerah Provinsi Lampung Nomor 5 Tahun 2024 Tentang Tanggung Jawab Sosial Dan Lingkungan Perusahaan Diterbitkan Di Biro Hukum,2024 Dengan Subjek Tanggung Jawab Sosial Dan Lingkungan Perusahaan',
    year: 2024,
    downloads: 2,
    views: 4,
    kategori: 1,
    abstrak: 'https://jdih.lampungprov.go.id/uploads/abstrak/2024/02/abstrak_1717125396848.pdf',
    fileverasing: '',
    teu: 'LAMPUNG (PROVINSI), BIRO HUKUM',
    singkatan: 'PERDA',
    tglundang: '12 Februari 2024',
    subjek: 'Tanggung Jawab Sosial Dan Lingkungan Perusahaan',
    status: "Masih Berlaku",
    sumber: 'LD 2024 (5); 16 hlm',
    tptterbit: 'BIRO HUKUM, 2024',
    bidang: 'Hukum Tata Negara',
    bahasa: 'INDONESIA',
    lokasi: 'Biro Hukum Provinsi Lampung',
    link: 'https://jdih.lampungprov.go.id/product-hukum/provinsi/11103/pdf/tanggung-jawab-sosial-dan-lingkungan-perusahaan?req-download=file'
  },
  {
    id: 4,
    date: '22',
    month: 'Jan',
    number: 1,
    title: 'PERATURAN GUBERNUR Lampung Nomor 1 Tahun 2024',
    description:
      'Peraturan Gubernur Lampung Nomor 1 Tahun 2024 Tentang Perubahan Kedua Atas Peraturan Gubernur Lampung Nomor 59 Tahun 2021 Tentang Susunan Organisasi, Tugas Dan Fungsi, Serta Tata Kerja Perangkat Daerah Diterbitkan Di Biro Hukum,2024 Dengan Subjek SOTK',
    year: 2024,
    downloads: 2,
    views: 4,
    kategori: 2,
    abstrak: 'https://jdih.lampungprov.go.id/uploads/abstrak/2024/01/abstrak_1710816413954.pdf',
    fileverasing: '',
    teu: 'LAMPUNG (PROVINSI), BIRO HUKUM',
    singkatan: 'PERGUB',
    tglundang: '22 Januari 2024',
    subjek: 'SOTK',
    status: "Masih Berlaku",
    sumber: '	BD 2024 (1) : 66 HLM',
    tptterbit: 'BIRO HUKUM, 2024',
    bidang: 'Hukum Tata Negara',
    bahasa: 'INDONESIA',
    lokasi: 'Biro Hukum Provinsi Lampung',
    link: 'https://jdih.lampungprov.go.id/product-hukum/provinsi/10973/pdf/perubahan-kedua-atas-peraturan-gubernur-lampung-nomor-59-tahun-2021-tentang-susunan-organisasi,-tugas-dan-fungsi,-serta-tata-kerja-perangkat-daerah?req-download=file'
  },
  {
    id: 5,
    date: '22',
    month: 'Jan',
    number: 2,
    title: 'PERATURAN GUBERNUR Lampung Nomor 2 Tahun 2024',
    description:
      'Peraturan Gubernur Lampung Nomor 2 Tahun 2024 Tentang Perubahan Kedua Atas Peraturan Gubernur Lampung Nomor 59 Tahun 2021 Tentang Susunan Organisasi, Tugas Dan Fungsi, Serta Tata Kerja Perangkat Daerah Diterbitkan Di Biro Hukum,2024 Dengan Subjek SOTK',
    year: 2024,
    downloads: 2,
    views: 4,
    kategori: 2,
    abstrak: 'https://jdih.lampungprov.go.id/uploads/abstrak/2024/01/abstrak_1710816413954.pdf',
    fileverasing: '',
    teu: 'LAMPUNG (PROVINSI), BIRO HUKUM',
    singkatan: 'PERGUB',
    tglundang: '22 Januari 2024',
    subjek: 'SOTK',
    status: "Masih Berlaku",
    sumber: '	BD 2024 (1) : 66 HLM',
    tptterbit: 'BIRO HUKUM, 2024',
    bidang: 'Hukum Tata Negara',
    bahasa: 'INDONESIA',
    lokasi: 'Biro Hukum Provinsi Lampung',
    link: 'https://jdih.lampungprov.go.id/product-hukum/provinsi/10973/pdf/perubahan-kedua-atas-peraturan-gubernur-lampung-nomor-59-tahun-2021-tentang-susunan-organisasi,-tugas-dan-fungsi,-serta-tata-kerja-perangkat-daerah?req-download=file'
  },
  {
    id: 6,
    date: '22',
    month: 'Jan',
    number: 3,
    title: 'PERATURAN GUBERNUR Lampung Nomor 3 Tahun 2024',
    description:
      'Peraturan Gubernur Lampung Nomor 1 Tahun 2024 Tentang Perubahan Kedua Atas Peraturan Gubernur Lampung Nomor 59 Tahun 2021 Tentang Susunan Organisasi, Tugas Dan Fungsi, Serta Tata Kerja Perangkat Daerah Diterbitkan Di Biro Hukum,2024 Dengan Subjek SOTK',
    year: 2024,
    downloads: 2,
    views: 4,
    kategori: 2,
    abstrak: 'https://jdih.lampungprov.go.id/uploads/abstrak/2024/01/abstrak_1710816413954.pdf',
    fileverasing: '',
    teu: 'LAMPUNG (PROVINSI), BIRO HUKUM',
    singkatan: 'PERGUB',
    tglundang: '22 Januari 2024',
    subjek: 'SOTK',
    status: "Masih Berlaku",
    sumber: '	BD 2024 (1) : 66 HLM',
    tptterbit: 'BIRO HUKUM, 2024',
    bidang: 'Hukum Tata Negara',
    bahasa: 'INDONESIA',
    lokasi: 'Biro Hukum Provinsi Lampung',
    link: 'https://jdih.lampungprov.go.id/product-hukum/provinsi/10973/pdf/perubahan-kedua-atas-peraturan-gubernur-lampung-nomor-59-tahun-2021-tentang-susunan-organisasi,-tugas-dan-fungsi,-serta-tata-kerja-perangkat-daerah?req-download=file'
  },
  {
    id: 7,
    date: '22',
    month: 'Jan',
    number: 1,
    title: 'KEPUTUSAN GUBERNUR Lampung Nomor 1 Tahun 2024',
    description:
      'Keputusan Gubernur Lampung Nomor 1 Tahun 2024 Tentang Perubahan Kedua Atas Peraturan Gubernur Lampung Nomor 59 Tahun 2021 Tentang Susunan Organisasi, Tugas Dan Fungsi, Serta Tata Kerja Perangkat Daerah Diterbitkan Di Biro Hukum,2024 Dengan Subjek SOTK',
    year: 2024,
    downloads: 2,
    views: 4,
    kategori: 3,
    abstrak: 'https://jdih.lampungprov.go.id/uploads/abstrak/2024/01/abstrak_1710816413954.pdf',
    fileverasing: '',
    teu: 'LAMPUNG (PROVINSI), BIRO HUKUM',
    singkatan: 'PERGUB',
    tglundang: '22 Januari 2024',
    subjek: 'SOTK',
    status: "Masih Berlaku",
    sumber: '	BD 2024 (1) : 66 HLM',
    tptterbit: 'BIRO HUKUM, 2024',
    bidang: 'Hukum Tata Negara',
    bahasa: 'INDONESIA',
    lokasi: 'Biro Hukum Provinsi Lampung',
    link: 'https://jdih.lampungprov.go.id/product-hukum/provinsi/10973/pdf/perubahan-kedua-atas-peraturan-gubernur-lampung-nomor-59-tahun-2021-tentang-susunan-organisasi,-tugas-dan-fungsi,-serta-tata-kerja-perangkat-daerah?req-download=file'
  },
  {
    id: 8,
    date: '22',
    month: 'Jan',
    number: 2,
    title: 'KEPUTUSAN GUBERNUR Lampung Nomor 2 Tahun 2024',
    description:
      'Keputusan Gubernur Lampung Nomor 2 Tahun 2024 Tentang Perubahan Kedua Atas Peraturan Gubernur Lampung Nomor 59 Tahun 2021 Tentang Susunan Organisasi, Tugas Dan Fungsi, Serta Tata Kerja Perangkat Daerah Diterbitkan Di Biro Hukum,2024 Dengan Subjek SOTK',
    year: 2024,
    downloads: 2,
    views: 4,
    kategori: 3,
    abstrak: 'https://jdih.lampungprov.go.id/uploads/abstrak/2024/01/abstrak_1710816413954.pdf',
    fileverasing: '',
    teu: 'LAMPUNG (PROVINSI), BIRO HUKUM',
    singkatan: 'PERGUB',
    tglundang: '22 Januari 2024',
    subjek: 'SOTK',
    status: "Masih Berlaku",
    sumber: '	BD 2024 (1) : 66 HLM',
    tptterbit: 'BIRO HUKUM, 2024',
    bidang: 'Hukum Tata Negara',
    bahasa: 'INDONESIA',
    lokasi: 'Biro Hukum Provinsi Lampung',
    link: 'https://jdih.lampungprov.go.id/product-hukum/provinsi/10973/pdf/perubahan-kedua-atas-peraturan-gubernur-lampung-nomor-59-tahun-2021-tentang-susunan-organisasi,-tugas-dan-fungsi,-serta-tata-kerja-perangkat-daerah?req-download=file'
  },
  {
    id: 9,
    date: '22',
    month: 'Jan',
    number: 3,
    title: 'KEPUTUSAN GUBERNUR Lampung Nomor 3 Tahun 2024',
    description:
      'Keputusan Gubernur Lampung Nomor 3 Tahun 2024 Tentang Perubahan Kedua Atas Peraturan Gubernur Lampung Nomor 59 Tahun 2021 Tentang Susunan Organisasi, Tugas Dan Fungsi, Serta Tata Kerja Perangkat Daerah Diterbitkan Di Biro Hukum,2024 Dengan Subjek SOTK',
    year: 2024,
    downloads: 2,
    views: 4,
    kategori: 3,
    abstrak: 'https://jdih.lampungprov.go.id/uploads/abstrak/2024/01/abstrak_1710816413954.pdf',
    fileverasing: '',
    teu: 'LAMPUNG (PROVINSI), BIRO HUKUM',
    singkatan: 'PERGUB',
    tglundang: '22 Januari 2024',
    subjek: 'SOTK',
    status: "Masih Berlaku",
    sumber: '	BD 2024 (1) : 66 HLM',
    tptterbit: 'BIRO HUKUM, 2024',
    bidang: 'Hukum Tata Negara',
    bahasa: 'INDONESIA',
    lokasi: 'Biro Hukum Provinsi Lampung',
    link: 'https://jdih.lampungprov.go.id/product-hukum/provinsi/10973/pdf/perubahan-kedua-atas-peraturan-gubernur-lampung-nomor-59-tahun-2021-tentang-susunan-organisasi,-tugas-dan-fungsi,-serta-tata-kerja-perangkat-daerah?req-download=file'
  },
  {
    id: 10,
    date: '22',
    month: 'Jan',
    number: 1,
    title: 'INSTRUKSI GUBERNUR Lampung Nomor 1 Tahun 2024',
    description:
      'Instruksi Gubernur Lampung Nomor 1 Tahun 2024 Tentang Perubahan Kedua Atas Peraturan Gubernur Lampung Nomor 59 Tahun 2021 Tentang Susunan Organisasi, Tugas Dan Fungsi, Serta Tata Kerja Perangkat Daerah Diterbitkan Di Biro Hukum,2024 Dengan Subjek SOTK',
    year: 2024,
    downloads: 2,
    views: 4,
    kategori: 4,
    abstrak: 'https://jdih.lampungprov.go.id/uploads/abstrak/2024/01/abstrak_1710816413954.pdf',
    fileverasing: '',
    teu: 'LAMPUNG (PROVINSI), BIRO HUKUM',
    singkatan: 'PERGUB',
    tglundang: '22 Januari 2024',
    subjek: 'SOTK',
    status: "Masih Berlaku",
    sumber: '	BD 2024 (1) : 66 HLM',
    tptterbit: 'BIRO HUKUM, 2024',
    bidang: 'Hukum Tata Negara',
    bahasa: 'INDONESIA',
    lokasi: 'Biro Hukum Provinsi Lampung',
    link: 'https://jdih.lampungprov.go.id/product-hukum/provinsi/10973/pdf/perubahan-kedua-atas-peraturan-gubernur-lampung-nomor-59-tahun-2021-tentang-susunan-organisasi,-tugas-dan-fungsi,-serta-tata-kerja-perangkat-daerah?req-download=file'
  },
  {
    id: 11,
    date: '22',
    month: 'Jan',
    number: 2,
    title: 'INSTRUKSI GUBERNUR Lampung Nomor 2 Tahun 2024',
    description:
      'Instruksi Gubernur Lampung Nomor 2 Tahun 2024 Tentang Perubahan Kedua Atas Peraturan Gubernur Lampung Nomor 59 Tahun 2021 Tentang Susunan Organisasi, Tugas Dan Fungsi, Serta Tata Kerja Perangkat Daerah Diterbitkan Di Biro Hukum,2024 Dengan Subjek SOTK',
    year: 2024,
    downloads: 2,
    views: 4,
    kategori: 4,
    abstrak: 'https://jdih.lampungprov.go.id/uploads/abstrak/2024/01/abstrak_1710816413954.pdf',
    fileverasing: '',
    teu: 'LAMPUNG (PROVINSI), BIRO HUKUM',
    singkatan: 'PERGUB',
    tglundang: '22 Januari 2024',
    subjek: 'SOTK',
    status: "Masih Berlaku",
    sumber: '	BD 2024 (1) : 66 HLM',
    tptterbit: 'BIRO HUKUM, 2024',
    bidang: 'Hukum Tata Negara',
    bahasa: 'INDONESIA',
    lokasi: 'Biro Hukum Provinsi Lampung',
    link: 'https://jdih.lampungprov.go.id/product-hukum/provinsi/10973/pdf/perubahan-kedua-atas-peraturan-gubernur-lampung-nomor-59-tahun-2021-tentang-susunan-organisasi,-tugas-dan-fungsi,-serta-tata-kerja-perangkat-daerah?req-download=file'
  },
  {
    id: 12,
    date: '22',
    month: 'Jan',
    number: 3,
    title: 'INSTRUKSI GUBERNUR Lampung Nomor 3 Tahun 2024',
    description:
      'Instruksi Gubernur Lampung Nomor 3 Tahun 2024 Tentang Perubahan Kedua Atas Peraturan Gubernur Lampung Nomor 59 Tahun 2021 Tentang Susunan Organisasi, Tugas Dan Fungsi, Serta Tata Kerja Perangkat Daerah Diterbitkan Di Biro Hukum,2024 Dengan Subjek SOTK',
    year: 2024,
    downloads: 2,
    views: 4,
    kategori: 4,
    abstrak: 'https://jdih.lampungprov.go.id/uploads/abstrak/2024/01/abstrak_1710816413954.pdf',
    fileverasing: '',
    teu: 'LAMPUNG (PROVINSI), BIRO HUKUM',
    singkatan: 'PERGUB',
    tglundang: '22 Januari 2024',
    subjek: 'SOTK',
    status: "Masih Berlaku",
    sumber: '	BD 2024 (1) : 66 HLM',
    tptterbit: 'BIRO HUKUM, 2024',
    bidang: 'Hukum Tata Negara',
    bahasa: 'INDONESIA',
    lokasi: 'Biro Hukum Provinsi Lampung',
    link: 'https://jdih.lampungprov.go.id/product-hukum/provinsi/10973/pdf/perubahan-kedua-atas-peraturan-gubernur-lampung-nomor-59-tahun-2021-tentang-susunan-organisasi,-tugas-dan-fungsi,-serta-tata-kerja-perangkat-daerah?req-download=file'
  },
  {
    id: 13,
    date: '22',
    month: 'Jan',
    number: 11,
    title: 'SURAT KEPUTUSAN GUBERNUR Nomor 11 Tahun 2024',
    description:
      'Surat Keputusan Gubernur Nomor 11 Tahun 2024 Tentang Perubahan Kedua Atas Peraturan Gubernur Lampung Nomor 59 Tahun 2021 Tentang Susunan Organisasi, Tugas Dan Fungsi, Serta Tata Kerja Perangkat Daerah Diterbitkan Di Biro Hukum,2024 Dengan Subjek SOTK',
    year: 2024,
    downloads: 2,
    views: 4,
    kategori: 5,
    abstrak: 'https://jdih.lampungprov.go.id/uploads/abstrak/2024/01/abstrak_1710816413954.pdf',
    fileverasing: '',
    teu: 'LAMPUNG (PROVINSI), BIRO HUKUM',
    singkatan: 'PERGUB',
    tglundang: '22 Januari 2024',
    subjek: 'SOTK',
    status: "Masih Berlaku",
    sumber: '	BD 2024 (1) : 66 HLM',
    tptterbit: 'BIRO HUKUM, 2024',
    bidang: 'Hukum Tata Negara',
    bahasa: 'INDONESIA',
    lokasi: 'Biro Hukum Provinsi Lampung',
    link: 'https://jdih.lampungprov.go.id/product-hukum/provinsi/10973/pdf/perubahan-kedua-atas-peraturan-gubernur-lampung-nomor-59-tahun-2021-tentang-susunan-organisasi,-tugas-dan-fungsi,-serta-tata-kerja-perangkat-daerah?req-download=file'
  },
  {
    id: 14,
    date: '22',
    month: 'Jan',
    number: 27,
    title: 'SURAT KEPUTUSAN GUBERNUR Nomor 27 Tahun 2024',
    description:
      'Surat Keputusan Gubernur Nomor 2 Tahun 2024 Tentang Perubahan Kedua Atas Peraturan Gubernur Lampung Nomor 59 Tahun 2021 Tentang Susunan Organisasi, Tugas Dan Fungsi, Serta Tata Kerja Perangkat Daerah Diterbitkan Di Biro Hukum,2024 Dengan Subjek SOTK',
    year: 2024,
    downloads: 2,
    views: 4,
    kategori: 5,
    abstrak: 'https://jdih.lampungprov.go.id/uploads/abstrak/2024/01/abstrak_1710816413954.pdf',
    fileverasing: '',
    teu: 'LAMPUNG (PROVINSI), BIRO HUKUM',
    singkatan: 'PERGUB',
    tglundang: '22 Januari 2024',
    subjek: 'SOTK',
    status: "Masih Berlaku",
    sumber: '	BD 2024 (1) : 66 HLM',
    tptterbit: 'BIRO HUKUM, 2024',
    bidang: 'Hukum Tata Negara',
    bahasa: 'INDONESIA',
    lokasi: 'Biro Hukum Provinsi Lampung',
    link: 'https://jdih.lampungprov.go.id/product-hukum/provinsi/10973/pdf/perubahan-kedua-atas-peraturan-gubernur-lampung-nomor-59-tahun-2021-tentang-susunan-organisasi,-tugas-dan-fungsi,-serta-tata-kerja-perangkat-daerah?req-download=file'
  },
  {
    id: 15,
    date: '22',
    month: 'Jan',
    number: 12,
    title: 'SURAT KEPUTUSAN GUBERNUR Nomor 12 Tahun 2024',
    description:
      'Surat Keputusan Gubernur Nomor 12 Tahun 2024 Tentang Perubahan Kedua Atas Peraturan Gubernur Lampung Nomor 59 Tahun 2021 Tentang Susunan Organisasi, Tugas Dan Fungsi, Serta Tata Kerja Perangkat Daerah Diterbitkan Di Biro Hukum,2024 Dengan Subjek SOTK',
    year: 2024,
    downloads: 2,
    views: 4,
    kategori: 5,
    abstrak: 'https://jdih.lampungprov.go.id/uploads/abstrak/2024/01/abstrak_1710816413954.pdf',
    fileverasing: '',
    teu: 'LAMPUNG (PROVINSI), BIRO HUKUM',
    singkatan: 'PERGUB',
    tglundang: '22 Januari 2024',
    subjek: 'SOTK',
    status: "Masih Berlaku",
    sumber: '	BD 2024 (1) : 66 HLM',
    tptterbit: 'BIRO HUKUM, 2024',
    bidang: 'Hukum Tata Negara',
    bahasa: 'INDONESIA',
    lokasi: 'Biro Hukum Provinsi Lampung',
    link: 'https://jdih.lampungprov.go.id/product-hukum/provinsi/10973/pdf/perubahan-kedua-atas-peraturan-gubernur-lampung-nomor-59-tahun-2021-tentang-susunan-organisasi,-tugas-dan-fungsi,-serta-tata-kerja-perangkat-daerah?req-download=file'
  }
])
